daftar_vaksin/urls.py
from os import stat
from django.urls import path
from .views import list_tempat, filter_data, search, tambah_tempat, json
from .views import DaftarVaksinView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', list_tempat, name='list_tempat'),
    path('filter-data', filter_data, name='filter_data'),
    path('search', search, name='search'),
    path('tambah-tempat', tambah_tempat, name='tambah_tempat'),
    path('json/', json, name='json'),
    path('data', DaftarVaksinView.as_view()),
    path('articles/<int:pk>', DaftarVaksinView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home
from .views import load
from .views import forum
from .views import add_thread
from .views import test
from .views import load_flutter

urlpatterns = [
    path("load/", load, name = "load"),
    path("forum/<slug>/", forum, name = "forum"),
    path("Add-Thread/", add_thread, name = "add_thread"),
    path("test/", test, name = "test"),
    path("load-flutter/", load_flutter, name = "load_flutter"),
]

projectd02_uts/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path
from tesCovid.views import filter_test
from django.conf import settings
from django.conf.urls.static import static
from home.views import home

urlpatterns = [

    path('admin/', admin.site.urls),
    #path('', include('main.urls')),
    path('kamus-obat/', include('kamus_obat.urls')),
    path('daftar-vaksin/', include('daftar_vaksin.urls')),
    path('covid-test/', include('tesCovid.urls')),
    path('filter-test', filter_test, name='filter_test'),
    path('apotek/', include('apotek.urls')),
    path('', include('home.urls')),
    path('', include('account.urls')),
    re_path(r'^$', home, name='homepage'),
    path('artikel/', include('artikel.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daftar_vaksin/models.py
from django.db import models

class JenisVaksin(models.Model):
    Nama = models.CharField(max_length = 50)

    def __str__(self):
        return self.Nama

class Kota(models.Model):
    Nama = models.CharField(max_length = 50)

    def __str__(self):
        return self.Nama

class TempatVaksin(models.Model):
    Nama = models.CharField(max_length = 50, default = "Nama")
    Lokasi = models.CharField(max_length = 50, default="Lokasi")
    Kota = models.ForeignKey(Kota, on_delete = models.CASCADE, blank=True, null=True)
    JenisVaksin = models.ForeignKey(JenisVaksin, on_delete = models.CASCADE, blank=True, null=True)
    Jadwal = models.TextField(blank=True, null=True)
    LinkDaftar = models.URLField(blank=True, null=True)
    Foto = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return self.Nama

daftar_vaksin/forms.py
from .models import TempatVaksin
from django import forms

class TempatForm(forms.ModelForm):
    class Meta:
        model = TempatVaksin
        fields = ('Nama', 'Lokasi', 'Kota', 'JenisVaksin', 'Jadwal', 'LinkDaftar', 'Foto')

        widgets = {
            'Nama': forms.TextInput(attrs={'class': 'entry formEntry'}),
            'Lokasi': forms.TextInput(attrs={'class': 'entry formEntry'}),
            'Kota': forms.Select(attrs={'class': 'entry form-control'}),
            'JenisVaksin': forms.Select(attrs={'class': 'entry form-control'}),
            'Jadwal': forms.Textarea(attrs={'class': 'entry formEntry'}),
            'LinkDaftar': forms.URLInput(attrs={'class': 'entry formEntry'}),
            'Foto': forms.URLInput(attrs={'class': 'entry formEntry'}),
        }

daftar_vaksin/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseRedirect, request, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import TempatVaksin, Kota, JenisVaksin
from .forms import TempatForm
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import TempatVaksinSerializer

# Create your views here.
def list_tempat(request):
    tempat = TempatVaksin.objects.all().order_by('-id').distinct()
    banyakTempat = TempatVaksin.objects.count()
    kota = Kota.objects.all().values()
    jenis = JenisVaksin.objects.all().values()
    response = {'data' : tempat, 'kota' : kota, 'jenis' : jenis, 'banyakData' : banyakTempat}
    return render(request, 'list_tempat.html', response)

def filter_data(request):
    kota = request.GET.getlist('kota[]')
    jenis = request.GET.getlist('jenis[]')
    semuaTempat = TempatVaksin.objects.all().order_by('-id').distinct()
    if len(kota) > 0:
        semuaTempat = semuaTempat.filter(Kota__id__in = kota).distinct()
    if len(jenis) > 0:
        semuaTempat = semuaTempat.filter(JenisVaksin__id__in = jenis).distinct()
    tempat = render_to_string('list-tempat.html', {'data' : semuaTempat})
    return JsonResponse({'data' : tempat})

def search(request):
    banyakTempat = TempatVaksin.objects.count()
    tempatDicari = request.GET['cari']
    kota = Kota.objects.all().values()
    jenis = JenisVaksin.objects.all().values()
    tempat = TempatVaksin.objects.all().order_by('-id').distinct()
    tempatFiltered = TempatVaksin.objects.filter(Nama__icontains = tempatDicari).order_by('-id')
    if tempatDicari == '':
        response = {'data': tempat, 'kota' : kota, 'jenis' : jenis, 'banyakData' : banyakTempat}
        return render(request, 'list_tempat.html', response)
    else:
        response = {'data' : tempatFiltered, 'kota' : kota, 'jenis' : jenis, 'banyakData' : banyakTempat}
        return render(request, 'search_tempat.html', response)

def tambah_tempat(request):
    form = TempatForm(request.POST, request.FILES)
    response = {'form' : form}
    if (form.is_valid and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/daftar-vaksin')
    else:
        return render(request, 'form_tempat.html', response)

# Web Service UAS
@csrf_exempt
def json(request):
    products = TempatVaksin.objects.all()
    data = serializers.serialize('json', products)
    return HttpResponse(data, content_type="application/json")

class DaftarVaksinView(APIView):
    def get(self, request):
        lokasiVaksin = TempatVaksin.objects.all()
        serializer = TempatVaksinSerializer(lokasiVaksin, many = True)
        return Response({"lokasiVaksin": serializer.data})
    
    def post(self, request):
        lokasiVaksin = request.data.get('lokasiVaksin')

        serializer = TempatVaksinSerializer(data = lokasiVaksin)
        if serializer.is_valid(raise_exception=True):
            lokasiVaksin_saved = serializer.save()

        lokasiVaksin = TempatVaksin.objects.all()
        serializer = TempatVaksinSerializer(lokasiVaksin, many = True)
        return Response({"lokasiVaksin": serializer.data})

daftar_vaksin/templates/filter_tempat.html
<html>
    {% load static %}
    <script src="{% static 'js/filter.js'%}" type="text/javascript"></script>

    <h3>Lokasi</h3>
    {% for k in kota %}
    <input type="checkbox" class="filter" data-filter="kota" value="{{k.id}}">
    {{k.Nama}} <br>
    {% endfor %}
    <br>
    <h3>Jenis Vaksin</h3>
    {% for j in jenis %}
    <input type="checkbox" class="filter" data-filter="jenis" value="{{j.id}}">
    {{j.Nama}} <br>
    {% endfor %}

</html>

daftar_vaksin/templates/form_tempat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{% static 'css/form_tambah_lokasi.css'%}" rel="stylesheet" />
    <title>Tambah Lokasi Vaksin</title>
  </head>

  <body>
    <div class="head">
      <h1> <span class="title3">Tambah </span> Lokasi<span class="title2">Vaksin </span> </h1>
    </div>
    <br>
    <form action = "" method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
          <div class="form-group">
              <label for="id_Nama">Nama</label>
              <input type="text" class="form-control" placeholder="Nama Lokasi" name="Nama" required>
          </div>
          </br>

          <div class="form-group">
            <label for="id_Lokasi">Lokasi</label>
            <input type="text" class="form-control" placeholder="Daerah Lokasi" name="Lokasi" required>
          </div>
          </br>

          <div class="form-group">
            <label for="id_Kota">Kota</label>
            {{form.Kota}}
          </div>
          </br>

          <div class="form-group">
            <label for="id_JenisVaksin">Jenis Vaksin</label>
            {{form.JenisVaksin}}
          </div>
          </br>

          <div class="form-group">
              <label for="id_Jadwal">Jadwal</label>
              <textarea class="form-control" rows="3" name="Jadwal"></textarea>
          </div>
          </br>

          <div class="form-group">
              <label for="id_LinkDaftar">Link Pendaftaran</label>
              <input type="text" class="form-control" name="LinkDaftar">
              <small id="urlHelp" class="form-text text-muted">Masukkan link pendaftaran resmi vaksin.</small>
          </div>
          </br>

          <div class="form-group">
            <label for="id_effect">Link Gambar</label>
            <input type="text" class="form-control" name="Foto">
            <small id="urlHelp" class="form-text text-muted">Masukkan link foto lokasi vaksin.</small>
          </div>

          <div align='center'>
            <button type='submit' class="btn btn-outline-secondary" id="animate2">Tambah Lokasi</button>      
          </div>
      </div>
    </form>
    <br>
    <div align='center'>
      <a href="{% url 'list_tempat' %}" >
        <button class="btn btn-secondary" id="animate">Keluar</button>
      </a>  
    </div>
    <br>
    
  </body>
</html>

daftar_vaksin/templates/list-tempat.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link href="{% static 'css/daftar_vaksin.css'%}" rel="stylesheet" />

<p class="ajaxLoader">Loading Tempat</p>
{% if data %} 
{% for tmpt in data %}
<div class="col mb-1 zoom tempat-box">
  <div class="card h-100">
      <img src="{{tmpt.Foto}}" class="card-img-top gambarLokasi">
      <div class="card-body">
        <h5 class="card-title">{{ tmpt.Nama }}</h5>
        <p class="namaKota">{{ tmpt.Lokasi }}, {{ tmpt.Kota.Nama }}</p>
        <p class="namaVaksin">Jenis Vaksin: {{ tmpt.JenisVaksin.Nama }}</p>
        <p>{{ tmpt.Jadwal }}</p>
        <a href="{{ tmpt.LinkDaftar }}">
          <button class="btn btn-outline-secondary" id="animate2">Daftar</button>
        </a>
      </div>
    </div>
</div>
{% endfor %}
{% endif %}

daftar_vaksin/templates/list_tempat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{% static 'css/daftar_vaksin.css'%}" rel="stylesheet" />
    <title>Lindungi Peduli - Pendaftaran Vaksin</title>
    <link rel=icon href="{% static 'img/logokotak.png' %}" sizes="any" type="image/svg+xml">
  </head>

  {% include 'navbar.html' %}

  <body>
    <div>
      <div class="head">
        <h1> Lokasi<span class="title2">Vaksin </span> </h1>
      </div>
      
      <div>
        <div id="filter">
          <form action="/daftar-vaksin/search" class="search">
            <div class="input-group mb-3">
              <input name="cari" type="text" class="form-control" placeholder="Cari Lokasi Vaksin">
              <div class="input-group-append">
                <button class="btn btn-outline-secondary" id="animate" type="submit">Cari</button>
              </div>
            </div>
          </form>
          {% include 'filter_tempat.html' %}
          <br>
          {% if user.is_superuser %}
          <a href="{% url 'tambah_tempat' %}">
            <button class="btn btn-outline-secondary tambah" id="animate" >Tambahkan Lokasi Vaksin </button>
          </a>
          {% endif %}
        </div>

        <div class="isi"> 
          <div class="row row-cols-1 row-cols-md-3" id="filteredTempat">
            <p class="ajaxLoader">Loading Tempat</p>
              {% if data %} 
              {% for tmpt in data %}
              <div class="col mb-1 zoom tempat-box">
                <div class="card h-100">
                    <img src="{{tmpt.Foto}}" class="card-img-top gambarLokasi">
                    <div class="card-body">
                      <h5 class="card-title">{{ tmpt.Nama }}</h5>
                      <p class="namaKota">{{ tmpt.Lokasi }}, {{ tmpt.Kota.Nama }}</p>
                      <p class="namaVaksin">Jenis Vaksin: {{ tmpt.JenisVaksin.Nama }}</p>
                      <p>{{ tmpt.Jadwal }}</p>
                      <a href="{{ tmpt.LinkDaftar }}">
                        <button class="btn btn-outline-secondary" id="animate2">Daftar</button>
                      </a>
                    </div>
                  </div>
              </div>
              {% endfor %}
              {% endif %}
          </div>
        </div>
      </div>
    </div>
  </body>
  <script>
    $(document).ready(function(){
      var temp = document.getElementById("nav-daftar-vaksin");
        temp.classList.add("active");
      });
  </script>

</html>

daftar_vaksin/templates/search_tempat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{% static 'css/daftar_vaksin.css'%}" rel="stylesheet" />
    <title>Lindungi Peduli - Pendaftaran Vaksin</title>
    <link rel=icon href="{% static 'img/logokotak.png' %}" sizes="any" type="image/svg+xml">
  </head>

  {% include 'navbar.html' %}

  <body>
    <div>
      <div class="head">
        <h1> Lokasi<span class="title2">Vaksin </span> </h1>
      </div>
      
      <div>
        <div id="filter">
          <form action="/daftar-vaksin/search" class="search">
            <div class="input-group mb-3">
              <input name="cari" type="text" class="form-control" placeholder="Cari Lokasi Vaksin">
              <div class="input-group-append">
                <button class="btn btn-outline-secondary" id="animate" type="submit">Cari</button>
              </div>
            </div>
          </form>
          <h4> <span class="text-muted"> Hasil Pencarian untuk </span> {{request.GET.cari}} </h4>
          <br>
          {% if user.is_superuser %}
          <a href="{% url 'tambah_tempat' %}">
            <button class="btn btn-outline-secondary tambah" id="animate" >Tambahkan Lokasi Vaksin </button>
          </a>
          {% endif %}
        </div>

        <div class="isi"> 
          <div class="row row-cols-1 row-cols-md-3" id="filteredTempat">
              {% if data %} 
              {% for tmpt in data %}
              <div class="col mb-1 zoom tempat-box">
                <div class="card h-100">
                    <img src="{{tmpt.Foto}}" class="card-img-top gambarLokasi">
                    <div class="card-body">
                      <h5 class="card-title">{{ tmpt.Nama }}</h5>
                      <p class="namaKota">{{ tmpt.Lokasi }}, {{ tmpt.Kota.Nama }}</p>
                      <p class="namaVaksin">Jenis Vaksin: {{ tmpt.JenisVaksin.Nama }}</p>
                      <p>{{ tmpt.Jadwal }}</p>
                      <a href="{{ tmpt.LinkDaftar }}">
                        <button class="btn btn-outline-secondary" id="animate2">Daftar</button>
                      </a>
                    </div>
                  </div>
              </div>
              {% endfor %}
              {% endif %}
          </div>
        </div>
      </div>
    </div>

  </body>
  <script>
    $(document).ready(function(){
      var temp = document.getElementById("nav-daftar-vaksin");
        temp.classList.add("active");
      });
  </script>
</html>