home/urls.py
from django.urls import path
from .views import home
from .views import load
from .views import forum
from .views import add_thread
from .views import test
from .views import load_flutter

urlpatterns = [
    path("load/", load, name = "load"),
    path("forum/<slug>/", forum, name = "forum"),
    path("Add-Thread/", add_thread, name = "add_thread"),
    path("test/", test, name = "test"),
    path("load-flutter/", load_flutter, name = "load_flutter"),
]

kamus_obat/urls.py
from django.urls import path
from .views import delete_kamus, kamus, add_kamus, detil_kamus, load_data, search_kamus, delete_kamus, json_kamus, post_kamus, delete_flutter

app_name = 'kamus_obat'

urlpatterns = [
    path('', kamus, name='kamus-obat'),
    path('add-kamus/', add_kamus, name='add-kamus'),
    path('obat/<int:pk>', detil_kamus, name='detil-kamus'),
    path('load-more/', load_data, name="load-more"),
    path('search/', search_kamus, name="search-kamus"),
    path('obat/<int:pk>/delete', delete_kamus, name='delete-kamus'),
    path('json/', json_kamus, name="kamus-json"),
    path('post/', post_kamus, name="kamus-post"),
    path('delete-post/', delete_flutter, name="delete-post"),

]

projectd02_uts/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path
from tesCovid.views import filter_test
from django.conf import settings
from django.conf.urls.static import static
from home.views import home

urlpatterns = [

    path('admin/', admin.site.urls),
    #path('', include('main.urls')),
    path('kamus-obat/', include('kamus_obat.urls')),
    path('daftar-vaksin/', include('daftar_vaksin.urls')),
    path('covid-test/', include('tesCovid.urls')),
    path('filter-test', filter_test, name='filter_test'),
    path('apotek/', include('apotek.urls')),
    path('', include('home.urls')),
    path('', include('account.urls')),
    re_path(r'^$', home, name='homepage'),
    path('artikel/', include('artikel.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artikel/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from datetime import datetime, date
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify

# Create your models here.
class Artikel(models.Model):
    judul = models.CharField(max_length=255)
    # isi = models.TextField()
    isi = models.TextField()
    ringkasan = models.TextField()
    tanggal = models.DateField(auto_now_add=True)
    gambar = models.URLField()
    slug = AutoSlugField(populate_from='judul')
    kategori = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='artikel_like')
    jumlah_like = models.PositiveIntegerField(default=0)
    nama_penulis = models.CharField(max_length=255)
    # https://pypi.org/project/django-autoslug/

    def __str__(self):
        return self.judul + " | " + str(self.penulis)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        return super(Artikel, self).save(*args, **kwargs)

    def total_likes(self):
        return self.likes.count()

    def update_likes(self):
        self.jumlah_like = self.total_likes()
        self.save()

class Kategori(models.Model):
    nama = models.CharField(max_length=255)

    def __str__(self):
        return self.nama

class Komentar(models.Model):
    artikel = models.ForeignKey(Artikel, related_name='komen', on_delete=models.CASCADE)
    penulis = models.ForeignKey(User, on_delete=models.CASCADE)
    isi = models.TextField()
    tanggal = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{judul} - {penulis}'.format(judul=self.artikel.judul, penulis=self.nama_penulis)

kamus_obat/models.py
from django.db import models

# Create your models here.
class Kamus(models.Model):
    # image = models.ImageField(null=True, blank=True, upload_to='images/')
    image = models.URLField(max_length=600, blank=True, null=True)
    name = models.CharField(max_length=30, default='')
    description = models.TextField(default='')
    effect = models.CharField(max_length=100, default='')
    ingredients = models.TextField(default='')

kamus_obat/forms.py
from django import forms
from .models import Kamus

class KamusForm(forms.ModelForm):
    class Meta:
      model = Kamus
      fields = [
        'image',
        'name',
        'description',
        'effect',
        'ingredients',
      ]
    
    widgets = {
      'image': forms.URLInput(attrs={'class': 'formEntry'}),
    }

    ## Membuat attribut untuk setiap field
    # widgets = {
    #   'gambar': forms.FileInput(
    #     attrs = {
    #       'type' : 'image',
    #       'class': 'form-control-file',
    #     }
    #   ),
      
    # }

   

kamus_obat/views.py
from django.shortcuts import render

# Create your views here.
from .models import Kamus
from .forms import KamusForm
from django.http.response import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import QueryDict



@login_required(login_url='/admin/login/')
def add_kamus(request):
    form = KamusForm(request.POST, request.FILES)

    response = {
        'form' : form,
    }

    if (form.is_valid() and request.method == "POST"):
        form.save()
    
        c_id = int(Kamus.objects.latest('id').id)
        return HttpResponseRedirect("/kamus-obat/obat/{id}".format(id=c_id))

    return render(request, 'kamus_obat/kamus_form.html', response)



def kamus(request):
    total_data=Kamus.objects.count()
    kamus = Kamus.objects.all().values()[:6]
    response = {
        "kamus" : kamus,
        "total_data" : total_data,
        }
    return render(request, "kamus_obat/kamus.html", response)

def load_data(request):
    current = int(request.GET['current'])
    limit = int(request.GET['limit'])
    kamus = Kamus.objects.all().values()[current:current+limit]

    response=render_to_string('ajax/kamus.html',{'kamus':kamus})
    return JsonResponse({'kamus':response})

## Referensi: https://www.youtube.com/watch?v=8NPOwmtupiI&list=PLCC34OHNcOtr025c1kHSPrnP18YPB-NFi&index=7
@login_required(login_url='/admin/login/')
def delete_kamus(request, pk):
    kamus = Kamus.objects.get(id=pk)

    if (request.method =='POST'):
        kamus.delete()
        return HttpResponseRedirect('/kamus-obat/')
    response = {"kamus" : kamus}
    return render(request, "kamus_obat/kamus_delete.html", response)

## Referensi: https://www.youtube.com/watch?v=ZHSXaFfx84I&t=453s
def search_kamus(request):
    query = request.GET['query']
    kamus = Kamus.objects.filter(name__icontains=query)
    total = kamus.count()
    response = {
        "kamus" : kamus,
        "total" : total,
        
        }
    return render(request, "kamus_obat/kamus_search.html", response)


def detil_kamus(request, pk):
    kamus = Kamus.objects.get(id=pk)
    response = {"kamus" : kamus}
    return render(request, "kamus_obat/kamus_detil.html", response)


@csrf_exempt
def json_kamus(request):
    products = Kamus.objects.all()
    data = serializers.serialize('json', products)
    return HttpResponse(data, content_type="application/json")

@csrf_exempt
def post_kamus(request):
    if(request.method=='POST'):
        request_data = request.body
        request_data = json.loads(request_data.decode('utf-8'))
        data = QueryDict('',mutable=True)
        data.update(request_data)
        form_req = KamusForm(data)

        if form_req.is_valid():
            form_req.save()
        
        return HttpResponseRedirect("/kamus-obat/")

@csrf_exempt
def delete_flutter(request):
    if (request.method =='POST'):
        request_data = request.body
        pk = json.loads(request_data.decode('utf-8'))['pk']
        kamus = Kamus.objects.get(id=int(pk))
        kamus.delete()
        
    return HttpResponseRedirect('/kamus-obat/')
    

kamus_obat/templates/kamus_obat/kamus.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
        <head>
            <meta charset="UTF-8" />
            <title> Kamus Obat </title>
            <link rel="stylesheet" href="{% static '../static/CSS/kamus_desain.css' %}" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script type="text/javascript" src="{% static 'js/load.js' %}"></script>
        
        </head>
            <body>
            {% include 'navbar.html' %}

            <div class ="full-container">
                
                <div class="container">
                {% if request.user.is_superuser %}
                <div class="row">
                    <div class="col-auto mr-auto"></div>
                    <div class="col-auto"><a href="{% url 'kamus_obat:add-kamus' %}" class="btn btn-warning" style="text-align: right;">+ Tambahkan Obat</a>
                    </div>
                </div>
                {% endif %}

                
                
                <h1>
                    <span class='title'>Kamus</span><span class='title2'>Obat</span>
                </br>
                </br>
                </h1>
                    <nav class="navbar navbar-light" style="justify-content: center;">
                        <form class="form-inline" action="search">
                          <input name="query" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="display:block;">
                          <button class="btn btn-outline-info" type="submit">Search</button>
                        </br>
                        </br>
                        </form>
                    </nav>

                    <div class="card-group" id="products">
                        {% for obat in kamus %}
                        <div class="card-container">
                            <div class="card" style="width: 16rem;">
                                <div class="card-img-top"><img class="h-100 d-inline-block" src="{{ obat.image }}" alt="{{obat.name}}.jpg" onerror="this.onerror=null;this.src='https://safetyaustraliagroup.com.au/wp-content/uploads/2019/05/image-not-found.png';"></div>
                                <div class="card-body">
                                    <h5 class="card-title" style="margin-bottom: 30px;">{{ obat.name }}</h5>
                                    <a href="{% url 'kamus_obat:detil-kamus' pk=obat.id %}" class="btn btn-primary">Lihat Detail</a>
                                </div>
                            </div>
                        </div>
                        

                        {% endfor %}
                    </div>
                   <button id="loadMore" data-total="{{total_data}}" data-limit="6" class="btn btn-dark btn-sm">Load More</button>

                    </br>
                    </br>

                </div> 
            </div>
        </body>
          <script>
                $(document).ready(function(){
                var temp = document.getElementById("navbarDropdown");
                    temp.classList.add("active");
                });
            </script>
</html>

kamus_obat/templates/kamus_obat/kamus_delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <div class ="full-container">
        <head>
            <meta charset="UTF-8" />
            <title> Form Kamus </title>
            <link rel="stylesheet" href="{% static '../static/CSS/kamus_desain.css' %}" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>        
        </head>

        <body>
            {% include 'navbar.html' %}

            </br>
            </br>
            <form action='' method='POST' enctype='multipart/form-data'>

                {% csrf_token %}
                <div class="jumbotron jumbotron-fluid" style="background-color: brown;">
                    <div class="container">
                      <h1 class="display-4" style="color: white; font-weight: bold;">Warning!</h1>
                      <p class="lead" style="color: white;">Are you sure you want to delete "{{kamus.name}}" from Kamus? </p>
                      <p style="color: white;">You will not be able to retrive it.</p>
                      <button type="submit" class="btn btn-default">Confirm</button>
                      <a href="{% url 'kamus_obat:kamus-obat' %}" class="btn btn-secondary" style="margin-left: 2%;">Cancel</a>
                      </br>
                    </div>
                  </div>
            
            </form>
            </br>
            

        </body>
    </div>
</html>

kamus_obat/templates/kamus_obat/kamus_detil.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
        <head>
            <meta charset="UTF-8" />
            <title> {{ kamus.name }} </title>
            <link rel="stylesheet" href="{% static '../static/CSS/kamus_desain.css' %}" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>        
        </head>

    <body>
    {% include 'navbar.html' %}

    <div class ="full-container">
        <div class="container">
            <div class="details-container"> 

                <div class="row">
                    <div class="col-md-5">
                    </br>
                        <div class="detil-image"><img class="img-thumbnail" src="{{ kamus.image }}" alt="foto obat" style="width: 400px" onerror="this.onerror=null;this.src='https://safetyaustraliagroup.com.au/wp-content/uploads/2019/05/image-not-found.png';">
                        </div>
                    </div>
                        <div class="col-md-7"> 
                            <h2 class="nama-obat">{{ kamus.name }}</h2>
                            </br>
                            <hr class="my-4">
                            <h6><span class='title3'>Deskripsi :</span></h6>
                            <p>{{ kamus.description }}</p>
                            </br>
                            <hr class="my-4">
                            <h6><span class='title3'>Efek Samping :</span></h6>
                            <p>{{ kamus.effect }}</p>
                            </br>
                            <hr class="my-4">
                            <h6><span class='title3'>Komposisi :</span></h6>
                            <p>{{ kamus.ingredients }}</p>
                        </div>
                </div>

            </div>
            </br>
            </br>

            <a href="{% url 'kamus_obat:kamus-obat' %}" class="btn btn-secondary">Back</a>
            {% if user.is_superuser %}
            <a href="{% url 'kamus_obat:delete-kamus' pk=kamus.id %}" class="btn btn-danger">Delete</a>
            {% endif %}

            </br>
            </br>

        </div>
        </body>
    </div>
</html>

kamus_obat/templates/kamus_obat/kamus_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <div class ="full-container">
        <head>
            <meta charset="UTF-8" />
            <title> Form Kamus </title>
            <link rel="stylesheet" href="{% static '../static/CSS/kamus_desain.css' %}" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>        
        </head>

        <body>
            <div class="container">

            </br>
            <div class="title-tambah">
            <h3><span class='title2'>Tambahkan Kamus</span><span class='title'>Obat</span></h3>
            </div>

            <form action='' method='POST' enctype='multipart/form-data'>

                    <div class="form-group">
                    </br>
                    </br>
                        <label for="id_gambar">Gambar Obat</label>
                        <p>{{form.image}}</p>
                        <small id="urlHelp" class="form-text text-muted">Enter the link address of your image choice.</small>
                    </div>
                    </br>
                    <div class="form-group">
                        <label for="id_name">Nama Obat</label>
                        <input type="text" class="form-control" placeholder="Nama Obat" name="name">
                    </div>
                    </br>
                    <div class="form-group">
                        <label for="id_description">Deskripsi Obat</label>
                        <textarea class="form-control" rows="3" name="description"></textarea>
                    </div>
                    </br>
                    <div class="form-group">
                        <label for="id_effect">Efek Samping</label>
                        <input type="text" class="form-control" name="effect">
                    </div>
                    </br>
                    <div class="form-group">
                        <label for="id_ingredients">Komposisi</label>
                        <textarea class="form-control" rows="3" name="ingredients"></textarea>
                    </div>
                    </br>
                    </br>
                    <button type="submit" class="btn btn-warning">Submit</button>
                    <a href="{% url 'kamus_obat:kamus-obat' %}" class="btn btn-secondary" style="margin-left: 2%;">Cancel</a>
                    </br>                
            
            </form>
            </br>
        </div>
        </body>
    </div>
</html>

kamus_obat/templates/kamus_obat/kamus_search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
        <head>
            <meta charset="UTF-8" />
            <title> Search result </title>
            <link rel="stylesheet" href="{% static '../static/CSS/kamus_desain.css' %}" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        </head>
            <body>
                {% include 'navbar.html' %}

                <div class ="full-container">
                    
                    
                    <div class="container">
                        <h2 style="text-align: left;">
                        </br>
                        </br>
                            <span class="text-muted">Search result: </span>{{request.GET.query}}
                        </br>
                        </br>
                        </h2>
                        <nav class="navbar navbar-light" style="justify-content: center;">
                            <form class="form-inline" action="{% url 'kamus_obat:search-kamus' %}">
                            <input name="query" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-secondary" type="submit">Search</button>
                            </br>
                            </br>
                            </form>
                        </nav>

                        <div class="card-group" id="products">
                            {% for obat in kamus %}
                            <div class="card-container">
                                <div class="card" style="width: 16rem;">
                                    <div class="card-img-top"><img class="h-100 d-inline-block" src="{{ obat.image }}" alt="{{obat.name}}.jpg" onerror="this.onerror=null;this.src='https://safetyaustraliagroup.com.au/wp-content/uploads/2019/05/image-not-found.png';"></div>
                                    <div class="card-body">
                                        <h5 class="card-title" style="margin-bottom: 30px;">{{ obat.name }}</h5>
                                        <a href="{% url 'kamus_obat:detil-kamus' pk=obat.id %}" class="btn btn-primary">Lihat Detail</a>
                                    </div>
                                </div>
                            </div>
                            
                            {% endfor %}
                        </div>

                        {% if total == 0 %} 
                            </br>
                            </br>
                            <p class="text-muted" style="text-align: center;">Obat Tidak Ditemukan</p>
                        {% endif %}
                    </div>
                </div>
            </body>
</html>